import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  conatiner: {
    // justifyContent: 'center',
    // alignItems: 'center',
    // flex: 1,
  },
  text: {
    color: '#fff',
    fontSize: 30,
    fontWeight: 'bold',
    marginTop: 100,
    marginLeft: 35,
  },
  main_1: {
    backgroundColor: '#6d63ff',
    height: 300,
    borderBottomLeftRadius: 15,
    borderBottomRightRadius: 15,
  },
  text_Input: {
    borderWidth: 2,
    fontSize: 20,
    // borderRadius: 10,
    borderColor: '#000',
    width: '85%',
    paddingLeft: 15,
    borderTopLeftRadius: 10,
    borderBottomLeftRadius: 10,
    backgroundColor: 'white',
    // borderRightWidth: 0,
  },
  text_Veiw: {
    marginHorizontal: 35,
    flexDirection: 'row',
    marginTop: 20,
  },
  plus: {
    fontSize: 30,
    fontWeight: 'bold',
    color: '#000',
  },
  touch: {
    borderWidth: 2,
    borderColor: '#000',
    justifyContent: 'center',
    alignItems: 'center',
    borderTopRightRadius: 10,
    borderBottomRightRadius: 10,
    width: '15%',
    borderLeftWidth: 0,
    backgroundColor: 'white',
  },
  main_2: {
    position: 'relative',
    top: -52,
  },
  main_2_Text: {
    fontSize: 25,
    fontWeight: 'bold',
    color: '#fff',
    marginLeft: 35,
  },
  map: {
    borderWidth: 2,
    marginHorizontal: 35,
    marginVertical: 10,
    backgroundColor: '#fff',
    borderColor: '#e2e2e2',
    borderRadius: 10,
    // padding: 8,
    paddingVertical:10,
    paddingHorizontal:10,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  map_Text: {
    fontSize: 20,
    // fontWeight: 'bold',
    color: '#000',
    paddingLeft: 10,
  },
  delete_Btn: {
    fontSize: 15,
    padding: 2,
    justifyContent: 'center',
    alignItems: 'center',
    flex: 2,
    color: 'red',
  },
  button_View: {
    flexDirection: 'row',
  },
  edit_Btn: {
    fontSize: 15,
    padding: 2,
    justifyContent: 'center',
    alignItems: 'center',
    flex: 2,
    color: 'green',
  },
});
